#!/usr/bin/env python
# Copyright (C) 2007
#    Martin Heistermann, <mh at lulzmeister dot de>
#    Tim Grocki, <drogenkonsument at gmail dot com>
#
# This file is part of sponc.
#
# sponc is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sponc is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sponc.  If not, see <http://www.gnu.org/licenses/>.

import sys

try:
    import sponc
except ImportError:
    sys.path = ['..', '/usr/share/games'] + sys.path

    try:
        import sponc
    except ImportError:
        sys.stderr.write('ERROR: Cannot find sponc package: reinstall the game.\n')
        sys.exit(1)

if __name__ == '__main__':
    sponc.SponcApp.start()
